name: cricwatch ci

on:
  push:
  pull_request:

jobs:
  run-tests:

    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Go get
        run: go get -v -t -d ./...

      - name: Go build
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -o circwatch ./cmd/main.go

      - name: Go test
        run: go test -v ./...
